services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: flight-booking-api
    container_name: flight-booking-api
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
