# Render Deployment Configuration
version: 1
services:
  - type: web
    name: flight-booking-backend
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    scaling:
      minInstances: 1
      maxInstances: 3
